version: 2

sources:
  - name: fhv_raw_data
    description: Raw data sources for NYC For-Hire Vehicle (FHV) rides
    database: fhv_rides_ny # for bigquery replace this with project id
    schema: prod # for bigquery , replace this with dataset
    tables:
      - name: fhv_tripdata
        decription: Raw FHV trip data
        columns:
          - name: dispatching_base_num
            description: |
              The TLC Taxi Zone where the trip started 
            data_type: varchar
          
          - name: pickup_datetime
            description: Timestamp when meter was engaged
            data_type: timestamp  

          - name: dropOff_datetime
            description: Timestamp when meter was disengaged
            data_type: timestamp

          - name: PULocationID
            description: TLC Taxi Zone where trip started
            data_type: integer

          - name: DOLocationID
            description: TLC Taxi Zone where trip ended
            data_type: integer

          - name: SR_Flag
            description: |
              Indicates whether the trip was a shared ride (SR) or not.
                0: Not a shared ride
                1: Shared ride
            data_type: integer  
          
          - name: Affiliated_base_number
            description: |
              The TLC Taxi Zone where the affiliated base is located    
            data_type: varchar  


